### ISSUE TITLE
Segfault in dump

### ISSUE THREAD

**Issue by ashqqy** [AbraCat/stack#1]
Если указатель на буфер стека невалидный, то при вызове `stDumpFn`, дамп будет обращаться по адресу буфера без проверки на валидность.

Пример использования буфера, вызывающий segfault.
`Stack st = {}; handleErr(stCtor(&st, 3)); stDtor(&st); stDump(stdout, &st);`

Исправить баг можно добавив проверку на валидность адреса буфера стека в функцию дампа.

**Comment by AbraCat** [comment]
fixed in commit a43e3f7
