### ISSUE TITLE
segfault in stDtor

### ISSUE THREAD

**Issue by ashqqy** [AbraCat/stack#2]
Разберём фрагменты исходного кода:
Здесь аллоцируем память для буфера стека и в `data` записываем не тот адрес, который аллоцировали, а прибавляем к нему 1 (чтобы `data` указывал сразу на буфер без левой канарейки)
`st->data = (StackElem*)realloc(st->data == NULL ? NULL : st->data - 1, (new_capacity + 2) * sizeof(StackElem)) + 1;`

А в функции деструктора освобождаем указатель `data`, который не равен тому адресу, который мы аллоцировали!
`void stDtor(Stack* st)
{
    if (st == NULL)
        return;
    free(st->data);
}`

В результате чего получаем segfault при каждом(!) использовании функции stDtor

**Comment by AbraCat** [comment]
fixed in comit c65c9a8
